version: "3.7"
services:
  db:
    image: postgres:latest
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - ./init.db.sql:/docker-entrypoint-initdb.d/init.db.sql
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task-db
  task_service:
    build: ./task-service
    image: task-service-image
    ports:
      - "5050:5000"
    environment:
      PYTHONUNBUFFERED: 1
volumes:
  postgres-volume: {}