version: "3.7"
services:
  broker:
    image: redis:latest
    container_name: job_broker

  db:
    image: postgres:latest
    container_name: task_db
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - ./init.db.sql:/docker-entrypoint-initdb.d/init.db.sql
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task-db

  task_service:
    build: ./task-service
    image: task-service-image
    container_name: task_service
    volumes:
      - ./email-job/email_job.py:/app/email_job.py
    ports:
      - "5050:5000"
    environment:
      PYTHONUNBUFFERED: 1
    depends_on:
      - db
      - broker
      - job_worker

  job_worker:
    build: ./email-worker/.
    container_name: email_worker
    volumes:
      - ./email-job/email_job.py:/app/email_job.py
    environment:
      PYTHONUNBUFFERED: 1
    depends_on:
      - broker
volumes:
  postgres-volume: {}